### ISSUE TITLE
workbox in vuejs todo

### ISSUE THREAD

**Issue by mazipan** [mazipan/workbox-in-js-framework#1]
Planning to create example for these below case:

- [x] Using Workbox Webpack Plugin: generateSW
- [x] Using Workbox Webpack Plugin: injectManifest
- [ ] Using Workbox Build: generateSW
- [ ] Using Workbox Build: injectManifest
- [ ] Using Workbox CLI: generateSW
- [ ] Using Workbox CLI: injectManifest
