### ISSUE TITLE
workbox in angular todo

### ISSUE THREAD

**Issue by mazipan** [mazipan/workbox-in-js-framework#2]
Planning to create example for these below case:

- [x] Using Workbox Build: generateSW
- [x] Using Workbox Build: injectManifest
- [x] Using Workbox CLI: generateSW
- [x] Using Workbox CLI: injectManifest
