### ISSUE TITLE
workbox in react todo

### ISSUE THREAD

**Issue by mazipan** [mazipan/workbox-in-js-framework#3]
Planning to create example for these below case:

- [ ] Using Workbox Webpack Plugin: generateSW
- [ ] Using Workbox Webpack Plugin: injectManifest
- [x] Using Workbox Build: generateSW
- [x] Using Workbox Build: injectManifest
- [x] Using Workbox CLI: generateSW
- [x] Using Workbox CLI: injectManifest
